"""
Alert Service: automated alerts triggered on data changes.
Channels: console (always), email (SendGrid), SMS (Twilio), in-app.
"""

import os
import logging
from datetime import datetime, timezone
from typing import List, Optional
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

SENDGRID_API_KEY  = os.getenv("SENDGRID_API_KEY", "")
FROM_EMAIL        = os.getenv("FROM_EMAIL", "alerts@eduguard.edu")
TWILIO_SID        = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_TOKEN      = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM       = os.getenv("TWILIO_PHONE_FROM", "")


def _risk_emoji(level: str) -> str:
    return {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Low": "🟢"}.get(level, "⚪")


def _build_email_html(student, prediction, faculty_name: str) -> tuple[str, str]:
    """Build subject and HTML body for email alert."""
    subject = f"[EduGuard] {prediction['risk_level']} Risk Alert — {student.student_id}"
    factors_html = "".join([
        f"<li><b>{f['feature'].replace('_',' ').title()}</b>: {f['impact']} risk (SHAP: {f['shap_value']:+.3f})</li>"
        for f in (prediction.get("top_risk_factors") or [])[:3]
    ])
    body = f"""
    <div style="font-family:sans-serif;max-width:600px;margin:0 auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
      <div style="background:{'#e53e3e' if prediction['risk_level']=='Critical' else '#f6ad55' if prediction['risk_level']=='High' else '#4299e1'};padding:20px 24px;">
        <h2 style="color:white;margin:0;">{_risk_emoji(prediction['risk_level'])} {prediction['risk_level']} Risk Student Alert</h2>
        <p style="color:rgba(255,255,255,0.85);margin:6px 0 0;">EduGuard Early Warning System</p>
      </div>
      <div style="padding:24px;">
        <p>Dear {faculty_name},</p>
        <p>Student <b>{student.student_id} — {student.full_name}</b> has been flagged as <b>{prediction['risk_level']} Risk</b> with a probability of <b>{prediction['risk_probability']:.1%}</b>.</p>
        <table style="width:100%;border-collapse:collapse;margin:16px 0;">
          <tr style="background:#f7fafc;"><td style="padding:8px 12px;"><b>Attendance</b></td><td>{student.attendance_pct:.1f}%</td></tr>
          <tr><td style="padding:8px 12px;"><b>Internal Marks</b></td><td>{student.internal_marks:.1f}/100</td></tr>
          <tr style="background:#f7fafc;"><td style="padding:8px 12px;"><b>Assignment Rate</b></td><td>{student.assignment_submission_rate:.1f}%</td></tr>
          <tr><td style="padding:8px 12px;"><b>CGPA</b></td><td>{student.prev_semester_cgpa:.2f}</td></tr>
        </table>
        <p><b>Top Contributing Factors:</b></p>
        <ul>{factors_html}</ul>
        <p style="background:#fff5f5;border-left:4px solid #e53e3e;padding:12px;border-radius:4px;"><b>Recommended Action:</b> Schedule an immediate counseling session with this student.</p>
      </div>
      <div style="background:#f7fafc;padding:16px 24px;font-size:12px;color:#718096;">
        <p>This alert was automatically generated by EduGuard. Do not reply to this email.</p>
      </div>
    </div>
    """
    return subject, body


def send_email_alert(to_email: str, student, prediction: dict, faculty_name: str) -> bool:
    if not SENDGRID_API_KEY:
        logger.info(f"📧 [CONSOLE] Email alert for {student.student_id} to {to_email} (SendGrid not configured)")
        return False
    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail
        subject, body = _build_email_html(student, prediction, faculty_name)
        msg = Mail(from_email=FROM_EMAIL, to_emails=to_email, subject=subject, html_content=body)
        SendGridAPIClient(SENDGRID_API_KEY).send(msg)
        logger.info(f"📧 Email sent to {to_email} for {student.student_id}")
        return True
    except Exception as e:
        logger.error(f"Email failed: {e}")
        return False


def send_sms_alert(to_phone: str, student, prediction: dict) -> bool:
    if not (TWILIO_SID and TWILIO_TOKEN):
        logger.info(f"📱 [CONSOLE] SMS alert for {student.student_id} (Twilio not configured)")
        return False
    try:
        from twilio.rest import Client
        msg = (f"[EduGuard] {prediction['risk_level']} Risk: {student.student_id} "
               f"({student.full_name}) — {prediction['risk_probability']:.1%} probability. "
               f"Please intervene immediately.")
        Client(TWILIO_SID, TWILIO_TOKEN).messages.create(
            body=msg, from_=TWILIO_FROM, to=to_phone
        )
        return True
    except Exception as e:
        logger.error(f"SMS failed: {e}")
        return False


def create_and_fire_alert(
    db: Session,
    student,
    prediction: dict,
    trigger_reason: str = "update",
) -> Optional[object]:
    """
    Create alert record in DB and fire all channels.
    Only fires for High/Critical risk.
    """
    from ..models.database import Alert, AlertStatus, RiskLevel, User

    risk_level = prediction["risk_level"]
    if risk_level not in ("High", "Critical"):
        return None

    # Create DB record
    alert = Alert(
        student_id=student.id,
        risk_level=RiskLevel(risk_level),
        risk_probability=prediction["risk_probability"],
        message=f"Student {student.student_id} flagged as {risk_level} risk ({prediction['risk_probability']:.1%})",
        status=AlertStatus.PENDING,
        trigger_reason=trigger_reason,
    )
    db.add(alert)
    db.flush()

    # Get faculty to notify
    email_sent = False
    if student.assigned_faculty_id:
        faculty = db.query(User).filter_by(id=student.assigned_faculty_id).first()
        if faculty and faculty.email:
            alert.sent_to_email = faculty.email
            email_sent = send_email_alert(faculty.email, student, prediction, faculty.full_name)
            if faculty.phone:
                alert.sent_to_phone = faculty.phone
                send_sms_alert(faculty.phone, student, prediction)
    else:
        # Notify HOD of the department
        hod = db.query(User).filter_by(
            department_id=student.department_id, role="hod"
        ).first()
        if hod:
            alert.sent_to_email = hod.email
            email_sent = send_email_alert(hod.email, student, prediction, hod.full_name)

    alert.status = AlertStatus.SENT if email_sent else AlertStatus.PENDING
    logger.warning(
        f"🚨 ALERT [{risk_level}] {student.student_id} | "
        f"Prob: {prediction['risk_probability']:.1%} | "
        f"Trigger: {trigger_reason}"
    )
    return alert


def fire_batch_alerts(db: Session, students: list, predictions: list, trigger_reason: str = "batch"):
    """Fire alerts for all high/critical risk students in a batch."""
    count = 0
    for student, prediction in zip(students, predictions):
        alert = create_and_fire_alert(db, student, prediction, trigger_reason)
        if alert:
            count += 1
    db.commit()
    logger.info(f"✅ Batch alerts: {count} fired for {trigger_reason}")
    return count
